<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var frontend\models\search\RgnDistrict $searchModel
 */
$this->title = 'Region Districts';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="giiant-crud rgn-district-index">

	<?php //     echo $this->render('_search', ['model' =>$searchModel]);

	?>

    <div class="clearfix">
        <p class="pull-left">
			<?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
        </p>

        <div class="pull-right">


			<?=

			\yii\bootstrap\ButtonDropdown::widget(
				[
					'id'			 => 'giiant-relations',
					'encodeLabel'	 => false,
					'label'			 => '<span class="glyphicon glyphicon-paperclip"></span> ' . 'Relations',
					'dropdown'		 => [
						'options'		 => [
							'class' => 'dropdown-menu-right'
						],
						'encodeLabels'	 => false,
						'items'			 => [
							[
								'url'	 => ['rgn-city/index'],
								'label'	 => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Region City' . '</i>',
							],
							[
								'url'	 => ['rgn-postcode/index'],
								'label'	 => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Region Postcode' . '</i>',
							],
							[
								'url'	 => ['rgn-subdistrict/index'],
								'label'	 => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Region Subdistrict' . '</i>',
							],
						],
					],
					'options'		 => [
						'class' => 'btn-default'
					],
				]
			);

			?>
		</div>
    </div>


	<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h2>
				<i><?= 'Region Districts' ?></i>
			</h2>
		</div>

		<div class="panel-body">

			<div class="table-responsive">
				<?=

				GridView::widget([
					'layout'			 => '{summary}{pager}{items}{pager}',
					'dataProvider'		 => $dataProvider,
					'pager'				 => [
						'class'			 => yii\widgets\LinkPager::className(),
						'firstPageLabel' => 'First',
						'lastPageLabel'	 => 'Last',
					],
					'filterModel'		 => $searchModel,
					'tableOptions'		 => ['class' => 'table table-striped table-bordered table-hover'],
					'headerRowOptions'	 => ['class' => 'x'],
					'columns'			 => [
						[
							'class'		 => 'yii\grid\ActionColumn',
							'options'	 => [],
							'urlCreator' => function($action, $model, $key, $index)
						{
							// using the column name as key, not mapping to 'id' like the standard generator
							$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
							$params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
							return Url::toRoute($params);
						},
							'contentOptions' => ['nowrap' => 'nowrap']
						],
						'name',
						// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
						[
							'class'		 => yii\grid\DataColumn::className(),
							'attribute'	 => 'city_id',
							'options'	 => [],
							'value'		 => function ($model)
						{
							if ($rel = $model->getCity()->one())
							{
								return Html::a($rel->name, ['rgn-city/view', 'id' => $rel->id,], ['data-pjax' => 0]);
							}
							else
							{
								return '';
							}
						},
							'format' => 'raw',
						],
					],
				]);

				?>
			</div>

		</div>

	</div>

	<?php \yii\widgets\Pjax::end() ?>


</div>
