<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var frontend\models\RgnDistrict $model
*/

$this->title = 'Rgn District ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Rgn Districts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud rgn-district-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List RgnDistricts', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
                <?= $model->name ?>            </h2>
        </div>

        <div class="panel-body">



    <?php $this->beginBlock('frontend\models\RgnDistrict'); ?>

    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id',
            [
                'attribute'=>'status',
                'value'=>frontend\models\RgnDistrict::getStatusValueLabel($model->status),
            ],
        'number',
        'name',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'city_id',
    'value' => ($model->getCity()->one() ? Html::a($model->getCity()->one()->name, ['rgn-city/view', 'id' => $model->getCity()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
        'created_at',
        'updated_at',
        'deleted_at',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'createdBy_id',
    'value' => ($model->getCreatedBy()->one() ? Html::a($model->getCreatedBy()->one()->id, ['user/view', 'id' => $model->getCreatedBy()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'updatedBy_id',
    'value' => ($model->getUpdatedBy()->one() ? Html::a($model->getUpdatedBy()->one()->id, ['user/view', 'id' => $model->getUpdatedBy()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'deletedBy_id',
    'value' => ($model->getDeletedBy()->one() ? Html::a($model->getDeletedBy()->one()->id, ['user/view', 'id' => $model->getDeletedBy()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
    ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('RgnPostcodes'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Rgn Postcodes',
            ['rgn-postcode/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Rgn Postcode',
            ['rgn-postcode/create', 'RgnPostcode' => ['district_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-RgnPostcodes', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-RgnPostcodes ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRgnPostcodes(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-rgnpostcodes']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'rgn-postcode' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'rgn-postcode'
],
        'id',
			[
                'attribute'=>'status',
                'value' => function ($model) {
                    return frontend\models\RgnDistrict::getStatusValueLabel($model->status);
                }    
            ]        ,
        'postcode',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'subdistrict_id',
    'value' => function ($model) {
        if ($rel = $model->getSubdistrict()->one()) {
            return Html::a($rel->name, ['rgn-subdistrict/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'city_id',
    'value' => function ($model) {
        if ($rel = $model->getCity()->one()) {
            return Html::a($rel->name, ['rgn-city/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'province_id',
    'value' => function ($model) {
        if ($rel = $model->getProvince()->one()) {
            return Html::a($rel->name, ['rgn-province/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'country_id',
    'value' => function ($model) {
        if ($rel = $model->getCountry()->one()) {
            return Html::a($rel->name, ['rgn-country/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'created_at',
        'updated_at',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('RgnSubdistricts'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Rgn Subdistricts',
            ['rgn-subdistrict/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Rgn Subdistrict',
            ['rgn-subdistrict/create', 'RgnSubdistrict' => ['district_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-RgnSubdistricts', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-RgnSubdistricts ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRgnSubdistricts(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-rgnsubdistricts']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'rgn-subdistrict' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'rgn-subdistrict'
],
        'id',
			[
                'attribute'=>'status',
                'value' => function ($model) {
                    return frontend\models\RgnDistrict::getStatusValueLabel($model->status);
                }    
            ]        ,
        'number',
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'createdBy_id',
    'value' => function ($model) {
        if ($rel = $model->getCreatedBy()->one()) {
            return Html::a($rel->id, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'updatedBy_id',
    'value' => function ($model) {
        if ($rel = $model->getUpdatedBy()->one()) {
            return Html::a($rel->id, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['frontend\models\RgnDistrict'],
    'active'  => true,
],[
    'content' => $this->blocks['RgnPostcodes'],
    'label'   => '<small>Rgn Postcodes <span class="badge badge-default">'.count($model->getRgnPostcodes()->asArray()->all()).'</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['RgnSubdistricts'],
    'label'   => '<small>Rgn Subdistricts <span class="badge badge-default">'.count($model->getRgnSubdistricts()->asArray()->all()).'</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
