<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;
use frontend\models\menu\RgnCityMenu;

/**
 * @var yii\web\View $this
 * @var common\models\RgnCity $model
 */
$this->title = 'Region City ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Region Cities', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

?>
<div class="giiant-crud rgn-city-view">

    <!-- menu buttons -->
    <p class='pull-left'>
		<?= $model->menu->button('update'); ?>
		<?= RgnCityMenu::btn('create'); ?>
	</p>
    <p class="pull-right">
		<?= $model->menu->button('index'); ?>
	</p>

    <div class="clearfix"></div>

    <!-- flash message -->
	<?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
		<span class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span></button>
			<?= \Yii::$app->session->getFlash('deleteError') ?>
		</span>
	<?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
				<?= $model->name ?>
			</h2>
        </div>

        <div class="panel-body">



			<?php $this->beginBlock('common\models\RgnCity'); ?>

			<?=

			DetailView::widget([
				'model'		 => $model,
				'attributes' => [
					'id',
					[
						'attribute'	 => 'status',
						'value'		 => common\models\RgnCity::getStatusValueLabel($model->status),
					],
					'name',
					'abbreviation',
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'province_id',
						'value'		 => ($model->getProvince()->one() ? Html::a($model->getProvince()->one()->name, ['rgn-province/view', 'id' => $model->getProvince()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
				],
			]);

			?>

			<hr/>

			<?= $model->menu->button('delete'); ?>

			<?php $this->endBlock(); ?>



			<?php $this->beginBlock('RgnDistricts'); ?>

			<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Region Districts', ['rgn-district/index'], ['class' => 'btn text-muted btn-xs']
					)

					?>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Region District', ['rgn-district/create', 'RgnDistrict' => ['city_id' => $model->id]], ['class' => 'btn btn-success btn-xs']
					);

					?>
				</div>
			</div>

			<?php Pjax::begin(['id' => 'pjax-RgnDistricts', 'enableReplaceState' => false, 'linkSelector' => '#pjax-RgnDistricts ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

			<?=

			'<div class="table-responsive">' . \yii\grid\GridView::widget([
				'layout'		 => '{summary}{pager}<br/>{items}{pager}',
				'dataProvider'	 => new \yii\data\ActiveDataProvider(['query' => $model->getRgnDistricts(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-rgndistricts']]),
				'pager'			 => [
					'class'			 => yii\widgets\LinkPager::className(),
					'firstPageLabel' => 'First',
					'lastPageLabel'	 => 'Last'
				],
				'columns'		 => [
					[
						'class'			 => 'yii\grid\ActionColumn',
						'template'		 => '{view} {update}',
						'contentOptions' => ['nowrap' => 'nowrap'],
						'urlCreator'	 => function ($action, $model, $key, $index)
					{
						// using the column name as key, not mapping to 'id' like the standard generator
						$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
						$params[0] = 'rgn-district' . '/' . $action;
						return $params;
					},
						'buttons'	 => [],
						'controller' => 'rgn-district'
					],
					'id',
					'name',
				]
			])
			. '</div>'

			?>
			<?php Pjax::end() ?>
			<?php $this->endBlock() ?>



			<?=

			Tabs::widget(
				[
					'id'			 => 'relation-tabs',
					'encodeLabels'	 => false,
					'items'			 => [
						[
							'label'		 => '<b class=""># ' . $model->id . '</b>',
							'content'	 => $this->blocks['common\models\RgnCity'],
							'active'	 => true,
						],
						[
							'content'	 => $this->blocks['RgnDistricts'],
							'label'		 => '<small>Region Districts <span class="badge badge-default">' . count($model->getRgnDistricts()->asArray()->all()) . '</span></small>',
							'active'	 => false,
						],
					],
				]
			);

			?>

			<br/><br/>

			<?= common\widgets\Moderation::widget(['model' => $model]); ?>

        </div>
    </div>
</div>
