<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;
use frontend\models\access\RgnCountryAccess;
use common\widgets\Moderation;

/**
 * @var yii\web\View $this
 * @var frontend\models\RgnCountry $model
 */
$this->title = 'Rgn Country ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Rgn Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

?>
<div class="giiant-crud rgn-country-view">

    <!-- menu buttons -->
    <p class='pull-left'>
		<?= $model->operation->button('update'); ?>
		<?= RgnCountryAccess::button('create'); ?>
    </p>
    <p class="pull-right">
		<?= RgnCountryAccess::button('index'); ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
	<?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
		<span class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span></button>
			<?= \Yii::$app->session->getFlash('deleteError') ?>
		</span>
	<?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
				<?= $model->name ?>
			</h2>
        </div>

        <div class="panel-body">

			<?php $this->beginBlock('frontend\models\RgnCountry'); ?>

			<?=

			DetailView::widget([
				'model'		 => $model,
				'attributes' => [
					'id',
					[
						'attribute'	 => 'status',
						'value'		 => $model->statusLabel,
					],
					'name',
					'abbreviation',
				],
			]);

			?>

			<hr/>

			<?= $model->operation->button('delete'); ?>
			<?= $model->operation->button('restore'); ?>

			<?php $this->endBlock(); ?>



			<?php $this->beginBlock('RgnPostcodes'); ?>
			<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Rgn Postcodes', ['rgn-postcode/index'], ['class' => 'btn text-muted btn-xs']
					)

					?>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Rgn Postcode', ['rgn-postcode/create', 'RgnPostcode' => ['country_id' => $model->id]], ['class' => 'btn btn-success btn-xs']
					);

					?>
				</div></div><?php Pjax::begin(['id' => 'pjax-RgnPostcodes', 'enableReplaceState' => false, 'linkSelector' => '#pjax-RgnPostcodes ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
			<?=

			'<div class="table-responsive">' . \yii\grid\GridView::widget([
				'layout'		 => '{summary}{pager}<br/>{items}{pager}',
				'dataProvider'	 => new \yii\data\ActiveDataProvider(['query' => $model->getRgnPostcodes(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-rgnpostcodes']]),
				'pager'			 => [
					'class'			 => yii\widgets\LinkPager::className(),
					'firstPageLabel' => 'First',
					'lastPageLabel'	 => 'Last'
				],
				'columns'		 => [[
					'class'			 => 'yii\grid\ActionColumn',
					'template'		 => '{view} {update}',
					'contentOptions' => ['nowrap' => 'nowrap'],
					'urlCreator'	 => function ($action, $model, $key, $index)
				{
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = 'rgn-postcode' . '/' . $action;
					return $params;
				},
					'buttons'	 => [
					],
					'controller' => 'rgn-postcode'
					],
					'id',
					[
						'attribute'	 => 'status',
						'value'		 => function ($model)
						{
							return frontend\models\RgnCountry::getStatusValueLabel($model->status);
						}
					],
					'postcode',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
					[
						'class'		 => yii\grid\DataColumn::className(),
						'attribute'	 => 'subdistrict_id',
						'value'		 => function ($model)
						{
							if ($rel = $model->getSubdistrict()->one())
							{
								return Html::a($rel->name, ['rgn-subdistrict/view', 'id' => $rel->id,], ['data-pjax' => 0]);
							}
							else
							{
								return '';
							}
						},
							'format' => 'raw',
						],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
						[
							'class'		 => yii\grid\DataColumn::className(),
							'attribute'	 => 'district_id',
							'value'		 => function ($model)
							{
								if ($rel = $model->getDistrict()->one())
								{
									return Html::a($rel->name, ['rgn-district/view', 'id' => $rel->id,], ['data-pjax' => 0]);
								}
								else
								{
									return '';
								}
							},
								'format' => 'raw',
							],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
							[
								'class'		 => yii\grid\DataColumn::className(),
								'attribute'	 => 'city_id',
								'value'		 => function ($model)
								{
									if ($rel = $model->getCity()->one())
									{
										return Html::a($rel->name, ['rgn-city/view', 'id' => $rel->id,], ['data-pjax' => 0]);
									}
									else
									{
										return '';
									}
								},
									'format' => 'raw',
								],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
								[
									'class'		 => yii\grid\DataColumn::className(),
									'attribute'	 => 'province_id',
									'value'		 => function ($model)
									{
										if ($rel = $model->getProvince()->one())
										{
											return Html::a($rel->name, ['rgn-province/view', 'id' => $rel->id,], ['data-pjax' => 0]);
										}
										else
										{
											return '';
										}
									},
										'format' => 'raw',
									],
								]
							])
							. '</div>';

							?>
							<?php Pjax::end() ?>
							<?php $this->endBlock() ?>


							<?php $this->beginBlock('RgnProvinces'); ?>
							<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
									<?=

									Html::a(
										'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Rgn Provinces', ['rgn-province/index'], ['class' => 'btn text-muted btn-xs']
									)

									?>
									<?=

									Html::a(
										'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Rgn Province', ['rgn-province/create', 'RgnProvince' => ['country_id' => $model->id]], ['class' => 'btn btn-success btn-xs']
									);

									?>
								</div>
							</div>
							<?php Pjax::begin(['id' => 'pjax-RgnProvinces', 'enableReplaceState' => false, 'linkSelector' => '#pjax-RgnProvinces ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
							<?=

							'<div class="table-responsive">' . \yii\grid\GridView::widget([
								'layout'		 => '{summary}{pager}<br/>{items}{pager}',
								'dataProvider'	 => new \yii\data\ActiveDataProvider(['query' => $model->getRgnProvinces(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-rgnprovinces']]),
								'pager'			 => [
									'class'			 => yii\widgets\LinkPager::className(),
									'firstPageLabel' => 'First',
									'lastPageLabel'	 => 'Last'
								],
								'columns'		 => [[
									'class'			 => 'yii\grid\ActionColumn',
									'template'		 => '{view} {update}',
									'contentOptions' => ['nowrap' => 'nowrap'],
									'urlCreator'	 => function ($action, $model, $key, $index)
								{
									// using the column name as key, not mapping to 'id' like the standard generator
									$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
									$params[0] = 'rgn-province' . '/' . $action;
									return $params;
								},
									'buttons'	 => [
									],
									'controller' => 'rgn-province'
									],
									'id',
									[
										'attribute'	 => 'status',
										'value'		 => function ($model)
										{
											return frontend\models\RgnCountry::getStatusValueLabel($model->status);
										}
									],
									'number',
									'name',
									'abbreviation',
								]
							])
							. '</div>';

							?>
							<?php Pjax::end() ?>
							<?php $this->endBlock() ?>


							<?=

							Tabs::widget(
								[
									'id'			 => 'relation-tabs',
									'encodeLabels'	 => false,
									'items'			 => [
										[
											'label'		 => '<b class=""># ' . $model->id . '</b>',
											'content'	 => $this->blocks['frontend\models\RgnCountry'],
											'active'	 => true,
										],
										[
											'content'	 => $this->blocks['RgnPostcodes'],
											'label'		 => '<small>Rgn Postcodes <span class="badge badge-default">' . count($model->getRgnPostcodes()->asArray()->all()) . '</span></small>',
											'active'	 => false,
										],
										[
											'content'	 => $this->blocks['RgnProvinces'],
											'label'		 => '<small>Rgn Provinces <span class="badge badge-default">' . count($model->getRgnProvinces()->asArray()->all()) . '</span></small>',
											'active'	 => false,
										],
									],
								]
							);

							?>
						</div>
					</div>

					<br/>
					<?= Moderation::widget(['model' => $model]); ?>

</div>
