<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var common\models\RgnSubdistrict $model
 */
$this->title = 'Region Subdistrict ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Region Subdistricts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

?>
<div class="giiant-crud rgn-subdistrict-view">

    <!-- menu buttons -->
    <p class='pull-left'>
		<?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
		<?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
		<?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List RgnSubdistricts', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
	<?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
		<span class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<?= \Yii::$app->session->getFlash('deleteError') ?>
		</span>
	<?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
				<?= $model->name ?>
			</h2>
        </div>

        <div class="panel-body">



			<?php $this->beginBlock('common\models\RgnSubdistrict'); ?>

			<?=

			DetailView::widget([
				'model'		 => $model,
				'attributes' => [
					'id',
					[
						'attribute'	 => 'status',
						'value'		 => common\models\RgnSubdistrict::getStatusValueLabel($model->status),
					],
					'name',
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'district_id',
						'value'		 => ($model->getDistrict()->one() ? Html::a($model->getDistrict()->one()->name, ['rgn-district/view', 'id' => $model->getDistrict()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
				],
			]);

			?>

			<hr/>

			<?=

			Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id], [
				'class'			 => 'btn btn-danger',
				'data-confirm'	 => '' . 'Are you sure to delete this item?' . '',
				'data-method'	 => 'post',
			]);

			?>
			<?php $this->endBlock(); ?>



			<?php $this->beginBlock('RgnPostcodes'); ?>
			<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Region Postcodes', ['rgn-postcode/index'], ['class' => 'btn text-muted btn-xs']
					)

					?>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Region Postcode', ['rgn-postcode/create', 'RgnPostcode' => ['subdistrict_id' => $model->id]], ['class' => 'btn btn-success btn-xs']
					);

					?>
				</div>
			</div>
			<?php Pjax::begin(['id' => 'pjax-RgnPostcodes', 'enableReplaceState' => false, 'linkSelector' => '#pjax-RgnPostcodes ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
			<?=

			'<div class="table-responsive">' . \yii\grid\GridView::widget([
				'layout'		 => '{summary}{pager}<br/>{items}{pager}',
				'dataProvider'	 => new \yii\data\ActiveDataProvider(['query' => $model->getRgnPostcodes(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-rgnpostcodes']]),
				'pager'			 => [
					'class'			 => yii\widgets\LinkPager::className(),
					'firstPageLabel' => 'First',
					'lastPageLabel'	 => 'Last'
				],
				'columns'		 => [
					[
						'class'			 => 'yii\grid\ActionColumn',
						'template'		 => '{view} {update}',
						'contentOptions' => ['nowrap' => 'nowrap'],
						'urlCreator'	 => function ($action, $model, $key, $index)
					{
						// using the column name as key, not mapping to 'id' like the standard generator
						$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
						$params[0] = 'rgn-postcode' . '/' . $action;
						return $params;
					},
						'buttons'	 => [],
						'controller' => 'rgn-postcode'
					],
					'id',
					'postcode',
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
					[
						'class'		 => yii\grid\DataColumn::className(),
						'attribute'	 => 'district_id',
						'options'	 => [],
						'value'		 => function ($model)
					{
						if ($rel = $model->getDistrict()->one())
						{
							return Html::a($rel->name, ['rgn-district/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						}
						else
						{
							return '';
						}
					},
						'format' => 'raw',
					],
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
					[
						'class'		 => yii\grid\DataColumn::className(),
						'attribute'	 => 'city_id',
						'options'	 => [],
						'value'		 => function ($model)
					{
						if ($rel = $model->getCity()->one())
						{
							return Html::a($rel->name, ['rgn-city/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						}
						else
						{
							return '';
						}
					},
						'format' => 'raw',
					],
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
					[
						'class'		 => yii\grid\DataColumn::className(),
						'attribute'	 => 'province_id',
						'options'	 => [],
						'value'		 => function ($model)
					{
						if ($rel = $model->getProvince()->one())
						{
							return Html::a($rel->name, ['rgn-province/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						}
						else
						{
							return '';
						}
					},
						'format' => 'raw',
					],
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
					[
						'class'		 => yii\grid\DataColumn::className(),
						'attribute'	 => 'country_id',
						'options'	 => [],
						'value'		 => function ($model)
					{
						if ($rel = $model->getCountry()->one())
						{
							return Html::a($rel->name, ['rgn-country/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						}
						else
						{
							return '';
						}
					},
						'format' => 'raw',
					],
				]
			])
			. '</div>';

			?>
			<?php Pjax::end() ?>
			<?php $this->endBlock() ?>


			<?=

			Tabs::widget(
				[
					'id'			 => 'relation-tabs',
					'encodeLabels'	 => false,
					'items'			 => [ [
							'label'		 => '<b class=""># ' . $model->id . '</b>',
							'content'	 => $this->blocks['common\models\RgnSubdistrict'],
							'active'	 => true,
						], [
							'content'	 => $this->blocks['RgnPostcodes'],
							'label'		 => '<small>Region Postcodes <span class="badge badge-default">' . count($model->getRgnPostcodes()->asArray()->all()) . '</span></small>',
							'active'	 => false,
						],]
				]
			);

			?>
        </div>
    </div>
</div>
