<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var common\models\RgnPostcode $model
 */
$this->title = 'Region Postcode ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Region Postcodes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

?>
<div class="giiant-crud rgn-postcode-view">

    <!-- menu buttons -->
    <p class='pull-left'>
		<?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
		<?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
		<?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List RgnPostcodes', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
	<?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
		<span class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<?= \Yii::$app->session->getFlash('deleteError') ?>
		</span>
	<?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
				<?= $model->id ?>
			</h2>
        </div>

        <div class="panel-body">



			<?php $this->beginBlock('common\models\RgnPostcode'); ?>

			<?=

			DetailView::widget([
				'model'		 => $model,
				'attributes' => [
					'id',
					'postcode',
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'subdistrict_id',
						'value'		 => ($model->getSubdistrict()->one() ? Html::a($model->getSubdistrict()->one()->name, ['rgn-subdistrict/view', 'id' => $model->getSubdistrict()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'district_id',
						'value'		 => ($model->getDistrict()->one() ? Html::a($model->getDistrict()->one()->name, ['rgn-district/view', 'id' => $model->getDistrict()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'city_id',
						'value'		 => ($model->getCity()->one() ? Html::a($model->getCity()->one()->name, ['rgn-city/view', 'id' => $model->getCity()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'province_id',
						'value'		 => ($model->getProvince()->one() ? Html::a($model->getProvince()->one()->name, ['rgn-province/view', 'id' => $model->getProvince()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'country_id',
						'value'		 => ($model->getCountry()->one() ? Html::a($model->getCountry()->one()->name, ['rgn-country/view', 'id' => $model->getCountry()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
				],
			]);

			?>

			<hr/>

			<?=

			Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id], [
				'class'			 => 'btn btn-danger',
				'data-confirm'	 => '' . 'Are you sure to delete this item?' . '',
				'data-method'	 => 'post',
			]);

			?>
			<?php $this->endBlock(); ?>



			<?=

			Tabs::widget(
				[
					'id'			 => 'relation-tabs',
					'encodeLabels'	 => false,
					'items'			 => [
						[
							'label'		 => '<b class=""># ' . $model->id . '</b>',
							'content'	 => $this->blocks['common\models\RgnPostcode'],
							'active'	 => true,
						],
					],
				]
			);

			?>
        </div>
    </div>
</div>
