<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use kartik\select2\Select2;
use kartik\select2\Select2Asset;
use frontend\models\RgnCountry;
use frontend\models\menu\RgnProvinceMenu;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var frontend\models\search\RgnProvinceSearch $searchModel
 */
$this->title = 'Region Provinces';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="giiant-crud rgn-province-index">

	<?php //echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="clearfix">
        <p class="pull-left">
			<?= RgnProvinceMenu::btn('create'); ?>
		</p>

        <div class="pull-right">

			<?= RgnProvinceMenu::btn('deleted'); ?>

			<?=

			\yii\bootstrap\ButtonDropdown::widget(
				[
					'id'			 => 'giiant-relations',
					'encodeLabel'	 => false,
					'label'			 => '<span class="glyphicon glyphicon-paperclip"></span> ' . 'Relations',
					'dropdown'		 => [
						'options'		 => [
							'class' => 'dropdown-menu-right'
						],
						'encodeLabels'	 => false,
						'items'			 => [
							[
								'url'	 => ['rgn-city/index'],
								'label'	 => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Region City' . '</i>',
							],
							[
								'url'	 => ['rgn-postcode/index'],
								'label'	 => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Region Postcode' . '</i>',
							],
							[
								'url'	 => ['rgn-country/index'],
								'label'	 => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Region Country' . '</i>',
							],
						],
					],
					'options'		 => [
						'class' => 'btn-default'
					],
				]
			);

			?>
		</div>
    </div>


	<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h2>
				<i><?= $this->title ?></i>
			</h2>
		</div>

		<div class="panel-body">

			<div class="table-responsive">
				<?=

				GridView::widget([
					'layout'			 => '{summary}{pager}{items}{pager}',
					'dataProvider'		 => $dataProvider,
					'pager'				 => [
						'class'			 => yii\widgets\LinkPager::className(),
						'firstPageLabel' => 'First',
						'lastPageLabel'	 => 'Last',
					],
					'filterModel'		 => $searchModel,
					'tableOptions'		 => ['class' => 'table table-striped table-bordered table-hover'],
					'headerRowOptions'	 => ['class' => 'x'],
					'columns'			 => [

						[
							'class'		 => 'yii\grid\SerialColumn',
							'options'	 => [
								'width' => '40px',
							],
						],
						//'name',
						[
							"class"		 => \yii\grid\DataColumn::className(),
							"attribute"	 => 'name',
							"format"	 => "raw",
							"options"	 => [],
							"value"		 => function($model)
						{
							return $model->menu->anchor('view', $model->name);
						},
						],
						'abbreviation',
						// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
						[
							'class'		 => yii\grid\DataColumn::className(),
							'attribute'	 => 'country_id',
							'options'	 => [],
							'value'		 => function ($model)
						{
							if ($rel = $model->getCountry()->one())
							{
								return Html::a($rel->name, ['rgn-country/view', 'id' => $rel->id,], ['data-pjax' => 0]);
							}
							else
							{
								return '';
							}
						},
							'format' => 'raw',
							'filter' => Select2::widget([
								'model'			 => $searchModel,
								'attribute'		 => 'country_id',
								'data'			 => RgnCountry::asOption(),
								'options'		 => [
									'id' => 'rgnprovince-country_id',
								],
								'pluginOptions'	 =>
								[
									'placeholder'		 => 'Select or type Country',
									'multiple'			 => FALSE,
									'allowClear'		 => TRUE,
									'tags'				 => TRUE,
									'maximumInputLength' => 255,
								],
							]),
						],
					],
				]);

				?>
			</div>

		</div>

	</div>

	<?php \yii\widgets\Pjax::end() ?>


</div>
