<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;
use frontend\models\menu\RgnProvinceMenu;

/**
 * @var yii\web\View $this
 * @var common\models\RgnProvince $model
 */
$this->title = 'Region Province ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Region Provinces', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

?>
<div class="giiant-crud rgn-province-view">

    <!-- menu buttons -->
    <p class='pull-left'>
		<?= $model->menu->button('update'); ?>
		<?= RgnProvinceMenu::button('create'); ?>
	</p>
    <p class="pull-right">
		<?= $model->menu->button('index'); ?>
	</p>

    <div class="clearfix"></div>

    <!-- flash message -->
	<?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
		<span class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span></button>
			<?= \Yii::$app->session->getFlash('deleteError') ?>
		</span>
	<?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
				<?= $model->name ?>
			</h2>
        </div>

        <div class="panel-body">



			<?php $this->beginBlock('frontend\models\RgnProvince'); ?>

			<?=

			DetailView::widget([
				'model'		 => $model,
				'attributes' => [
					'id',
					[
						'attribute'	 => 'status',
						'value'		 => frontend\models\RgnProvince::getStatusValueLabel($model->status),
					],
					'name',
					'abbreviation',
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'country_id',
						'value'		 => ($model->getCountry()->one() ? Html::a($model->getCountry()->one()->name, ['rgn-country/view', 'id' => $model->getCountry()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
				],
			]);

			?>

			<hr/>

			<?= $model->menu->button('delete'); ?>

			<?php $this->endBlock(); ?>



			<?php $this->beginBlock('RgnCities'); ?>
			<div style='position: relative'>
				<div style='position:absolute; right: 0px; top: 0px;'>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Region Cities', ['rgn-city/index'], ['class' => 'btn text-muted btn-xs']
					)

					?>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Region City', ['rgn-city/create', 'RgnCity' => ['province_id' => $model->id]], ['class' => 'btn btn-success btn-xs']
					);

					?>
				</div>
			</div>
			<?php Pjax::begin(['id' => 'pjax-RgnCities', 'enableReplaceState' => false, 'linkSelector' => '#pjax-RgnCities ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
			<?=

			'<div class="table-responsive">' . \yii\grid\GridView::widget([
				'layout'		 => '{summary}{pager}<br/>{items}{pager}',
				'dataProvider'	 => new \yii\data\ActiveDataProvider(['query' => $model->getRgnCities(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-rgncities']]),
				'pager'			 => [
					'class'			 => yii\widgets\LinkPager::className(),
					'firstPageLabel' => 'First',
					'lastPageLabel'	 => 'Last'
				],
				'columns'		 => [
					[
						'class'		 => 'yii\grid\SerialColumn',
						'options'	 => [
							'width' => '40px',
						],
					],
					'name',
					'abbreviation',
					[
						"label"		 => 'Action',
						"class"		 => \yii\grid\DataColumn::className(),
						"options"	 => [
							"width" => "120px",
						],
						"format"	 => "raw",
						"value"		 => function($model)
					{
						return $model->menu->widgetDropdown();
					},
					],
				]
			])
			. '</div>';

			?>
			<?php Pjax::end() ?>
			<?php $this->endBlock() ?>



			<?=

			Tabs::widget(
				[
					'id'			 => 'relation-tabs',
					'encodeLabels'	 => false,
					'items'			 => [
						[
							'label'		 => '<b class=""># ' . $model->id . '</b>',
							'content'	 => $this->blocks['frontend\models\RgnProvince'],
							'active'	 => true,
						],
						[
							'content'	 => $this->blocks['RgnCities'],
							'label'		 => '<small>Region Cities <span class="badge badge-default">' . count($model->getRgnCities()->asArray()->all()) . '</span></small>',
							'active'	 => false,
						],
					],
				]
			);

			?>
			<br/><br/>

			<?= common\widgets\Moderation::widget(['model' => $model]); ?>

        </div>
    </div>
</div>
