<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var common\models\RgnProvince $model
 */
$this->title = 'Region Province ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Region Provinces', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

?>
<div class="giiant-crud rgn-province-view">

    <!-- menu buttons -->
    <p class='pull-left'>
		<?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
		<?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
		<?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List RgnProvinces', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
	<?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
		<span class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span></button>
			<?= \Yii::$app->session->getFlash('deleteError') ?>
		</span>
	<?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
				<?= $model->name ?>
			</h2>
        </div>

        <div class="panel-body">



			<?php $this->beginBlock('common\models\RgnProvince'); ?>

			<?=

			DetailView::widget([
				'model'		 => $model,
				'attributes' => [
					'id',
					[
						'attribute'	 => 'status',
						'value'		 => common\models\RgnProvince::getStatusValueLabel($model->status),
					],
					'name',
					'abbreviation',
					// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
					[
						'format'	 => 'html',
						'attribute'	 => 'country_id',
						'value'		 => ($model->getCountry()->one() ? Html::a($model->getCountry()->one()->name, ['rgn-country/view', 'id' => $model->getCountry()->one()->id,]) : '<span class="label label-warning">?</span>'),
					],
				],
			]);

			?>

			<hr/>

			<?=

			Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id], [
				'class'			 => 'btn btn-danger',
				'data-confirm'	 => '' . 'Are you sure to delete this item?' . '',
				'data-method'	 => 'post',
			]);

			?>
			<?php $this->endBlock(); ?>



			<?php $this->beginBlock('RgnCities'); ?>
			<div style='position: relative'>
				<div style='position:absolute; right: 0px; top: 0px;'>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Region Cities', ['rgn-city/index'], ['class' => 'btn text-muted btn-xs']
					)

					?>
					<?=

					Html::a(
						'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Region City', ['rgn-city/create', 'RgnCity' => ['province_id' => $model->id]], ['class' => 'btn btn-success btn-xs']
					);

					?>
				</div>
			</div>
			<?php Pjax::begin(['id' => 'pjax-RgnCities', 'enableReplaceState' => false, 'linkSelector' => '#pjax-RgnCities ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
			<?=

			'<div class="table-responsive">' . \yii\grid\GridView::widget([
				'layout'		 => '{summary}{pager}<br/>{items}{pager}',
				'dataProvider'	 => new \yii\data\ActiveDataProvider(['query' => $model->getRgnCities(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-rgncities']]),
				'pager'			 => [
					'class'			 => yii\widgets\LinkPager::className(),
					'firstPageLabel' => 'First',
					'lastPageLabel'	 => 'Last'
				],
				'columns'		 => [
					[
						'class'			 => 'yii\grid\ActionColumn',
						'template'		 => '{view} {update}',
						'contentOptions' => ['nowrap' => 'nowrap'],
						'urlCreator'	 => function ($action, $model, $key, $index)
					{
						// using the column name as key, not mapping to 'id' like the standard generator
						$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
						$params[0] = 'rgn-city' . '/' . $action;
						return $params;
					},
						'buttons'	 => [],
						'controller' => 'rgn-city'
					],
					'id',
					'name',
					'abbreviation',
				]
			])
			. '</div>';

			?>
			<?php Pjax::end() ?>
			<?php $this->endBlock() ?>



			<?=

			Tabs::widget(
				[
					'id'			 => 'relation-tabs',
					'encodeLabels'	 => false,
					'items'			 => [
						[
							'label'		 => '<b class=""># ' . $model->id . '</b>',
							'content'	 => $this->blocks['common\models\RgnProvince'],
							'active'	 => true,
						],
						[
							'content'	 => $this->blocks['RgnCities'],
							'label'		 => '<small>Region Cities <span class="badge badge-default">' . count($model->getRgnCities()->asArray()->all()) . '</span></small>',
							'active'	 => false,
						],
					],
				]
			);

			?>
			<br/><br/>

			<?= common\widgets\Moderation::widget(['model' => $model]); ?>

        </div>
    </div>
</div>
